
---
title: "About WAMWIKI"
linkTitle: "About"
weight: 20
menu:
  main:
    weight: 10
    
---



{{% blocks/lead %}}
Goldydocs is a sample site using the <a href="https://github.com/google/docsy">Docsy</a> Hugo theme that shows what it can do and provides you with a template site structure. It’s designed for you to clone and edit as much as you like. See the different sections of the documentation and site for more ideas.
{{% /blocks/lead %}}


{{< blocks/section >}}
<div class="col-12">
<h1 class="text-center">This is another section</h1>
</div>

{{< /blocks/section >}}

{{< blocks/section >}}

<div class="col-12">
<h1 class="text-center">This is another section</h1>
</div>

{{< /blocks/section >}} 

This website is an on-line resource containing information and resources for anyone interested in learning more about and applying quantitative genetic methods - but especially for those interested in using quantitative genetics in natural populations.

More advanced code will be added to the Github account linked to this website.


## What are "Animal models"?

In particular, we demonstrate the use of *the animal model*, a statistical model used to estimate genetic contributions to trait variation using population pedigrees. The animal model methodology finds its origin in animal and plant breeding, where it has been applied successfully for several decades. Since the late 1990s, an increasing number of studies have applied animal models to address evolutionary questions in wild populations.

An animal model uses the information on the resemblance among individuals of known relatedness to estimate how genes influence phenotypes. A major difference from other quantitative genetic methods - which are also based on this principle - is that an animal model is not restricted to one level of relatedness (e.g. parent-offspring). Instead, animal models simultaneously describe the resemblance among all individuals in a given data set, irrespective of their level of relatedness. One is thus able to make optimal use of the often complex and patchy pedigrees obtained from monitoring in wild populations.

If you are looking for some simple code to get started, go here: Animal model tutorials.

